version: '3'
services:
  db:
    image: postgres:11.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sample
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /tmp:/tmp
